// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSAfkbc48NvtSZ6OwVrDCpzVrYVj93AAM',
    appId: '1:36500912954:android:8f98621103a674d4f6ee03',
    messagingSenderId: '36500912954',
    projectId: 'the212',
    storageBucket: 'the212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3rhY_zRhjSTjXHe5dTYfuS1u5z0X4QI',
    appId: '1:36500912954:ios:68c85aa95b8c8f17f6ee03',
    messagingSenderId: '36500912954',
    projectId: 'the212',
    storageBucket: 'the212.firebasestorage.app',
    androidClientId: '36500912954-92uuhmqikk0fuhg2u6p6q1hd7stqbaie.apps.googleusercontent.com',
    iosClientId: '36500912954-dmvil4834e5hqm2r5ur0lsd0p073decg.apps.googleusercontent.com',
    iosBundleId: 'com.freshcodes.twoonetwomessenger',
  );

}